name: Manager
main: com.timvisee.manager.Manager
version: 0.1
author: timvisee
website: http://timvisee.com/
softdepend: [Vault, zPermissions] #hack to fix trove errors
commands:
   manager:
      description: The testing commands for the manager plugin.
      aliases: [m]
      usage: /manager node [permissionnode], groups, addmoney, submoney, getmoney [playername]